print("Markdown CheatSheet")
print("===================")
print("")
print("Heading")
print("-------")
print("#H1")
print("##H2")
print("###H3")
print("")
print("Bold")
print("----")
print("**bold text**")
print("")
print("Italic")
print("------")
print("*italicized text")
print("")
print("Blockquote")
print("----------")
print("> blockquote")
print("")
print("Ordered List")
print("------------")
print("1. First item")
print("2. Second item")
print("3. Third item")
print("")
print("Unordered List")
print("--------------")
print("- First item")
print("- Second item")
print("- Third item")
print("")
print("#")
print("#")
print("#")
